### ISSUE TITLE
Dependencies should be prefixed with "openmicroscopy"

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/infrastructure-extract-ansible-role#1]
```
Starting import 47320: role_name=cli-utils repo=openmicroscopy/ansible-role-cli-utils
Accessing branch: master
Parsing and validating meta data.
Setting role name to cli-utils
Parsing galaxy_tags
No galaxy_tags found in meta data.
Parsing platforms
Adding dependencies
Error parsing dependency Expecting dependency name format to match 'username.role_name', instead got basedeps
Parsing and validating README
Adding repo tags as role versions
Import completed
Status FAILED : warnings=1 errors=1
```

**Comment by joshmoore** [comment]
All current repos are now green: https://galaxy.ansible.com/roleadd#/

**Comment by manics** [comment]
@joshmoore Related issue: should dependencies of roles be versioned? e.g. https://github.com/openmicroscopy/ansible-role-cli-utils/pull/1

**Comment by joshmoore** [comment]
If possible, I'd think it would be good if a role could say which dependency it would depend on. I haven't tested that though. Optimal would be if only the top level role would need to be depended on, then all the "right" versions could come along. (Is there conflict detection though??)

**Comment by manics** [comment]
Any role can be used on it's own in a playbook so it's not possible to ensure the dependencies form a tree, so there isn't a "top-level" role.

> Is there conflict detection though?

No:
- https://github.com/ansible/ansible/issues/16909
- https://github.com/ansible/proposals/issues/23

**Comment by joshmoore** [comment]
> Any role can be used on it's own in a playbook so it's not possible to ensure the dependencies form a tree, so there isn't a "top-level" role.

Not necessarily _just one_ top-level one, but I could certainly see an `omero-server:1.0.0` or a `omero-web:1.0.0` which could depend on other particular versions. This would certainly simplify the likes of your recent omero-grid PR.

> conflict detection ... no

That's too bad.

**Comment by manics** [comment]
All production roles and playbooks are decoupled from this repository.
